# Generated by Django 4.0 on 2021-12-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Test',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
